// <auto-generated />
using System;
using CodeFirstExample.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirstExample.Migrations
{
    [DbContext(typeof(VoorbeeldDb))]
    [Migration("20230605125256_AddTableWithRelation")]
    partial class AddTableWithRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeFirstExample.Models.Voorbeeld", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Voorbeelden");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2023, 6, 5, 14, 52, 55, 971, DateTimeKind.Local).AddTicks(8847),
                            Name = "Test"
                        });
                });

            modelBuilder.Entity("CodeFirstExample.Models.VoorbeeldCategorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VoorbeeldCategorieen");
                });

            modelBuilder.Entity("VoorbeeldVoorbeeldCategorie", b =>
                {
                    b.Property<int>("VoorbeeldCategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("VoorbeeldsId")
                        .HasColumnType("int");

                    b.HasKey("VoorbeeldCategoriesId", "VoorbeeldsId");

                    b.HasIndex("VoorbeeldsId");

                    b.ToTable("VoorbeeldVoorbeeldCategorie");
                });

            modelBuilder.Entity("VoorbeeldVoorbeeldCategorie", b =>
                {
                    b.HasOne("CodeFirstExample.Models.VoorbeeldCategorie", null)
                        .WithMany()
                        .HasForeignKey("VoorbeeldCategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirstExample.Models.Voorbeeld", null)
                        .WithMany()
                        .HasForeignKey("VoorbeeldsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
